### PR TITLE
Add docstrings to all variables

### PR DESCRIPTION
**Pull request by szaghi**
Dear Jacob,

this the first PR I would like to make. 

The main changes are:
- Add docstrings to all variables in order to address to all FORD warnings.
- Add also some minor code-style-linting rules (space after comma, start from first column, avoid implicit none where not necessary, etc...)

Essentially, besides the addiction of all docstrings for addressing the FORD warnings on undocumented variables, I have dove some code linting accordingly to my feeling (I do not like very much blank lines like you :-). Feel free to discharged my PR: the coding styles are obviously very personal and you may not like mine.

My best regards,
Stefano

### CODE REVIEW

**Comment by jacobwilliams** [comment]
I'll take a look at what you did when I get a chance.  :)

**Comment by szaghi** [comment]
Do not worry, take all the time you need. I will almost absent for the next two weeks. See you soon

**Comment by jacobwilliams** [comment]
I accepted some of them, but kept some of my original formatting.

**Comment by szaghi** [comment]
great! thank you very much!

**Pull request merged**
